import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto(process.argv[2] || process.env.TEST_URL || 'http://127.0.0.1:5173');
await page.locator('.prompt-card').waitFor();
await page.evaluate(() => document.fonts.ready);
await page.locator('.studio-photo img').scrollIntoViewIfNeeded();
await page.waitForFunction(() => document.querySelector('.studio-photo img').naturalWidth > 0);
await page.evaluate(() => window.scrollTo(0, 0));
await mkdir('test-results', { recursive: true });
await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
assert.equal(await page.locator('.prompt-card').count(), 1);
assert.match(await page.locator('#detail-body').innerText(), /<Picture 1>/);
await page.locator('#search').fill('breeze');
assert.equal(await page.locator('.prompt-card').count(), 1);
await page.locator('#search').fill('nonexistent scene');
assert.equal(await page.locator('.prompt-card').count(), 0);
await page.getByRole('button', { name: 'Reset pencarian' }).click();
await page.getByRole('combobox', { name: 'Filter status' }).click();
await page.getByRole('option', { name: 'Working', exact: true }).click();
assert.equal(await page.locator('.prompt-card').count(), 0);
await page.getByRole('combobox', { name: 'Filter status' }).click();
await page.getByRole('option', { name: 'Semua status', exact: true }).click();
await page.getByRole('combobox', { name: 'Filter tag' }).click();
await page.screenshot({ path: 'test-results/dropdown-desktop.png' });
await page.getByRole('combobox', { name: 'Filter tag' }).press('End');
await page.getByRole('combobox', { name: 'Filter tag' }).press('Enter');
assert.match(page.url(), /tag=/);
await page.locator('#reset-filters').click();
await page.getByRole('combobox', { name: 'Urutkan prompt' }).click();
await page.getByRole('combobox', { name: 'Urutkan prompt' }).press('Escape');
assert.equal(await page.getByRole('combobox', { name: 'Urutkan prompt' }).getAttribute('aria-expanded'), 'false');
await page.locator('[data-mode="i2va"]').click();
assert.equal(await page.locator('.prompt-card').count(), 1);
await page.locator('.card-bookmark').click();
await page.locator('[data-collection="favorites"]').click();
assert.equal(await page.locator('.prompt-card').count(), 1);
await page.reload();
await page.locator('.prompt-card').waitFor();
await page.locator('[data-tab="notes"]').click();
assert.match(await page.locator('#detail-body').innerText(), /Variables to Test/);
assert.equal(await page.locator('[data-collection="templates"]').count(), 0);
await page.locator('[data-collection="guides"]').click();
assert.equal(await page.locator('.prompt-card').count(), 2);
await page.locator('[data-collection="all"]').click();
await page.locator('.open-prompt').click();
const link = page.url();
assert.match(link, /prompt=experiments/);
await page.reload();
await page.locator('.prompt-card').waitFor();
assert.match(await page.locator('.detail h2').innerText(), /Art to Life/);
await page.locator('[data-action="theme"]').click();
await page.screenshot({ path: 'test-results/desktop-dark.png', fullPage: true });
await page.reload();
await page.locator('.prompt-card').waitFor();
assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
await page.locator('[data-action="theme"]').click();
await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
await page.locator('[data-action="copy"]').click();
assert.match(await page.evaluate(() => navigator.clipboard.readText()), /integrated_multimodal_description:/);
const downloadEvent = page.waitForEvent('download');
await page.locator('[data-action="download"]').click();
assert.match((await downloadEvent).suggestedFilename(), /\.md$/);
for (const width of [390, 320]) {
  await page.setViewportSize({ width, height: 844 });
  await page.locator('[data-action="back"]').click();
  assert.equal(await page.locator('.prompt-card').isVisible(), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: `test-results/mobile-${width}.png`, fullPage: true });
  await page.getByRole('combobox', { name: 'Filter status' }).click();
  const popup = await page.getByRole('listbox', { name: 'Filter status' }).boundingBox();
  assert.ok(popup.x >= 0 && popup.x + popup.width <= width);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: `test-results/dropdown-mobile-${width}.png` });
  await page.getByRole('combobox', { name: 'Filter status' }).press('Escape');
  await page.locator('.open-prompt').click();
  assert.equal(await page.locator('#detail').isVisible(), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: `test-results/mobile-detail-${width}.png`, fullPage: true });
}
assert.deepEqual(errors, []);
await browser.close();
console.log('Browser checks passed: search, filters, favorites, resources, notes, links, theme, copy, download, desktop and mobile.');
